### ISSUE TITLE
Class:DBHandler Method:selectAll

### ISSUE THREAD

**Issue by M3f1st0** [M3f1st0/MiuZiKs_Official#1]
MethodName: selectAll
Class:DBHandler

I have tried to replace the selectAllCities method in LogInController class, with sellectAll method, but I get errors. I believe that it is not possible to put "?" wildcard character in places other than the WHERE clause of the sql syntax. Solution for this could be to concat the strings with the use of "+".
(See method:returnColumnBasedOnCriteria Class:DBHandler)

Can you please investigate?

**Comment by cwsexton** [comment]
I'm on the case like Columbo.

**Comment by cwsexton** [comment]
You were right, ? are parameters and so can only replace values not table/field names so I amended the method to use concat strings and now it works, the methods that call it just need to send in the column name and table name as a string and then they will get the list of everything in that column back. So hopefully we can lose a few SelectAll... methods.

**Comment by M3f1st0** [comment]
Awesome as always! So the issue is considered resolved.
